name: wond3rcard
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  awesome_dio_interceptor: ^1.3.0
  dio: ^5.7.0
  flutter_riverpod: ^2.6.1
  fpdart: ^1.1.1
  hooks_riverpod: ^2.6.1
  logger: ^2.5.0
  retrofit: ^4.4.1
  heroicons: ^0.10.0
  pinput: ^5.0.0
  responsive_builder: ^0.7.1
  go_router: ^14.6.1
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  crypto: ^3.0.3
  uuid: ^4.5.1
  fluttertoast: ^8.2.8
  flutter_hooks: ^0.20.5
  flutter_colorpicker: ^1.1.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.1
  location: ^6.0.2
  geocoding: ^3.0.0
  hive_flutter: ^1.1.0
  file_picker: ^8.0.5
  qr_flutter: ^4.1.0
  fvm: ^3.2.1
  flutter_svg: ^2.0.17
  flutter_cache_manager: ^3.4.1
  cached_network_image: ^3.4.0
  smart_wrap: 0.0.1
  geolocator: ^13.0.2
  geolocator_web: ^4.1.1
  google_maps_flutter_web: ^0.5.10+1
  http: ^1.3.0
  google_places_flutter: ^2.0.9
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.4
  flutter_custom_clippers: ^2.1.0
  mime: ^2.0.0
  html: ^0.15.5
  universal_html: ^2.2.4
  http_parser: ^4.0.2
  syncfusion_flutter_charts: 
  fl_chart: ^0.70.2
  intl: ^0.18.1
  url_launcher: ^6.3.1
  flutter_animate: ^4.5.2
  simple_animations: ^5.1.0
  scrollable_positioned_list: ^0.3.8
  animated_card: ^2.0.0
  marquee: ^2.3.0
  shimmer: ^3.0.0
  qr_code_tools: ^0.2.0
  mobile_scanner: ^7.0.0
  permission_handler: ^12.0.0+1
  screenshot: ^3.0.0
  flutter_to_pdf: ^0.4.0

dev_dependencies:
  flutter_launcher_icons: "^0.14.3"
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.6.4
  build_runner: ^2.4.9
  mobkit_dashed_border: ^0.0.7
  freezed: ^2.4.5
  json_serializable: ^6.9.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "images/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "images/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "images/app_icon.png"  
  
flutter:
  uses-material-design: true

  assets:
    - images/
    - images/wonder_card_logo.png
    - images/behance.png

  fonts:
    - family: Barlow
      fonts:
        - asset: fonts/Barlow-Regular.ttf
